### ISSUE TITLE
Csp frame-src error

### ISSUE THREAD

**Issue by dszubartvirtua** [FATCHIP-GmbH/plugin-magento2-computop#4]
Hi,
We have a problem with refused frame by csp when we use creditcard payment with iframe mode for version 1.0.8.
![Screenshot from 2024-12-18 11-41-10](https://github.com/user-attachments/assets/5819094c-4cd2-4e9e-9d45-510aab6b8416)
Could you please add hosts also to frame-src in csp_whitelist.xml ?
Thanks

**Comment by markusmichalski-fc** [comment]
We added it here:
https://github.com/FATCHIP-GmbH/plugin-magento2-computop/commit/7643a682fb6a757d21abbca6fc464c693fa33a10

This will be included in the next release of the plugin.
